naveen="welecome to my world solution"
print( naveen)
print(type(naveen))
print(len(naveen))
print(naveen.index("r"))
print(naveen.isdigit())
print(naveen.rstrip("solution"))
print(naveen.lower())
print(naveen.title())
print(naveen.isnumeric())
print(naveen.casefold())
print(naveen.lstrip())
print(naveen.isalpha())
print(naveen.removeprefix("world"))
print(naveen.casefold())